/**
 * The report viewer in the browser: draws a report the page did not render at
 * build time, and wires the rows' filters on whichever report is shown.
 *
 * The markup is the same as the server render in src/pages/report/index.astro
 * (same elements, classes and ids), so one stylesheet and one `wireReport()`
 * serve both. Edit them together.
 *
 * Report text is untrusted: with `?src=` it comes from whoever wrote the link.
 * Every string from a report goes into the page as a text node or through
 * `textContent`; nothing here parses HTML, and the only `href`s set are the
 * row anchors and the docs URLs the page passes in.
 */
import {
  coverageSummary,
  groupDiagnostics,
  locationOf,
  optionsText,
  viewRows,
} from './report-view.js';

/** `h('p', { class: 'x' }, 'text', child)`: an element; strings become text nodes. */
function h(tag, attrs = {}, ...children) {
  const el = document.createElement(tag);
  for (const [k, v] of Object.entries(attrs)) {
    if (v === false || v === null || v === undefined) continue;
    if (k === 'style') for (const [p, val] of Object.entries(v)) el.style.setProperty(p, val);
    else el.setAttribute(k, v === true ? '' : String(v));
  }
  for (const c of children.flat(Infinity)) {
    if (c === null || c === undefined || c === false) continue;
    el.append(typeof c === 'string' || typeof c === 'number' ? document.createTextNode(String(c)) : c);
  }
  return el;
}

const code = (text, cls) => h('code', cls ? { class: cls } : {}, text);

/** Replace the article's content with `report`, drawn. */
export function renderReport(article, report, { docs }) {
  const cov = coverageSummary(report);
  const options = optionsText(report);
  const rows = viewRows(report);

  const head = h(
    'header',
    { class: 'r-head' },
    h('h2', { id: 'report-title', tabindex: '-1' }, h('span', { class: 'r-kicker' }, 'Target'), ' ', code(report.target)),
    h(
      'dl',
      { class: 'r-meta' },
      h('div', {}, h('dt', {}, 'Generated by'), h('dd', {}, code(report.generatedBy))),
      h('div', {}, h('dt', {}, 'Options'), h('dd', {}, options === null ? 'none' : code(options))),
      h(
        'div',
        {},
        h('dt', {}, 'Files'),
        h(
          'dd',
          {},
          report.files.length === 0
            ? 'none'
            : h(
                'details',
                { class: 'r-files' },
                h('summary', {}, `${report.files.length} file${report.files.length === 1 ? '' : 's'}`),
                h('ul', {}, report.files.map((f) => h('li', {}, code(f)))),
              ),
        ),
      ),
      // Optional in the schema: reports written before `reads` existed lack it.
      Array.isArray(report.reads)
        ? h(
            'div',
            {},
            h('dt', {}, 'Catalog slots read'),
            h(
              'dd',
              {},
              report.reads.length === 0
                ? 'none'
                : h(
                    'details',
                    { class: 'r-files' },
                    h('summary', {}, `${report.reads.length} slot${report.reads.length === 1 ? '' : 's'}`),
                    h('ul', {}, report.reads.map((s) => h('li', {}, code(s)))),
                  ),
            ),
          )
        : null,
    ),
  );

  const coverage = h(
    'section',
    { class: 'r-sec', 'aria-labelledby': 'h-coverage' },
    h('h3', { id: 'h-coverage' }, 'Coverage'),
    h(
      'div',
      { class: 'covmatrix r-bar' },
      h(
        'div',
        { class: 'cm-row' },
        h('span', { class: 'cm-name' }, report.target),
        h(
          'span',
          { class: 'cm-bar', 'aria-hidden': 'true' },
          cov.classes.filter((c) => c.count > 0).map((c) => h('span', { class: `cm-seg ${c.seg}`, style: { width: `${c.width}%` } })),
        ),
      ),
    ),
    h(
      'ul',
      { class: 'r-counts' },
      cov.classes.map((c) =>
        h(
          'li',
          {},
          h('i', { class: c.seg, 'aria-hidden': 'true' }),
          h('span', { class: 'r-cls' }, c.id),
          h('b', {}, String(c.count)),
          h('span', { class: 'r-pct' }, c.pct === null ? '—' : `${c.pct}%`),
          h('span', { class: 'r-blurb' }, c.blurb),
        ),
      ),
    ),
    h('p', { class: 'r-cli' }, h('span', {}, 'As the terminal prints it'), code(cov.cliLine)),
    h(
      'p',
      { class: 'r-note' },
      `${cov.total} row${cov.total === 1 ? '' : 's'}. A percentage measures this target’s own surface; it doesn’t rank targets against each other (`,
      h('a', { href: docs.coverage }, 'why'),
      ').',
    ),
  );

  const diagList = (items, withReason) =>
    h(
      'ul',
      { class: 'r-diags' },
      items.map((d) => {
        const at = locationOf(d);
        return h(
          'li',
          { class: `r-diag sev-${d.severity}` },
          h(
            'p',
            { class: 'd-line' },
            h('span', { class: 'sev' }, d.severity),
            ' ',
            h('a', { class: 'd-code', href: docs.diagnostics }, d.code),
            at ? [' ', code(at, 'd-loc')] : null,
          ),
          h('p', { class: 'd-msg' }, d.message),
          typeof d.hint === 'string' ? h('p', { class: 'd-hint' }, `↳ ${d.hint}`) : null,
          withReason ? h('p', { class: 'd-reason' }, h('span', {}, 'Reason:'), ' ', d.reason) : null,
        );
      }),
    );

  const groups = groupDiagnostics(report.diagnostics);
  const diagnostics = h(
    'section',
    { class: 'r-sec', 'aria-labelledby': 'h-diagnostics' },
    h('h3', { id: 'h-diagnostics' }, 'Diagnostics ', h('span', { class: 'r-n' }, String(report.diagnostics.length))),
    h('p', { class: 'r-note' }, 'The whole build’s diagnostics, not only this target’s: one an exporter raised starts with its target’s name.'),
    groups.length === 0
      ? h('p', { class: 'r-empty' }, 'None.')
      : groups.map((g) => [h('h4', {}, `${g.label} · ${g.items.length}`), diagList(g.items, false)]),
  );

  const suppressed = h(
    'section',
    { class: 'r-sec', 'aria-labelledby': 'h-suppressed' },
    h('h3', { id: 'h-suppressed' }, 'Suppressed ', h('span', { class: 'r-n' }, String(report.suppressed.length))),
    h('p', { class: 'r-note' }, 'Warnings and infos silenced by check.suppress in the config, each with the reason its entry gives.'),
    report.suppressed.length === 0 ? h('p', { class: 'r-empty' }, 'None.') : diagList(report.suppressed, true),
  );

  article.replaceChildren(head, coverage, diagnostics, suppressed, rowsSection(report, rows, cov));
}

function rowsSection(report, rows, cov) {
  const radios = [{ id: '', label: 'All', count: cov.total }, ...cov.classes.map((c) => ({ id: c.id, label: c.id, count: c.count }))];
  return h(
    'section',
    { class: 'r-sec', 'aria-labelledby': 'h-rows' },
    h('h3', { id: 'h-rows' }, 'Rows'),
    h(
      'p',
      { class: 'r-note' },
      'One row per target variable. Open a variable for the command that traces it back to what was authored.',
    ),
    h(
      'div',
      { class: 'r-filters', 'data-role': 'filters' },
      h(
        'fieldset',
        { class: 'r-seg' },
        h('legend', {}, 'Class'),
        radios.map((r) =>
          h(
            'label',
            {},
            h('input', { type: 'radio', name: 'r-class', value: r.id, checked: r.id === '' }),
            h('span', {}, r.label, ' ', h('small', {}, String(r.count))),
          ),
        ),
      ),
      h(
        'div',
        { class: 'r-search' },
        h('label', { for: 'r-search' }, 'Search'),
        h('input', { type: 'search', id: 'r-search', placeholder: 'variable, slot or note', autocomplete: 'off', spellcheck: 'false' }),
      ),
      h('p', { class: 'r-status', 'data-role': 'status', 'aria-live': 'polite' }),
    ),
    rows.length === 0
      ? h('p', { class: 'r-empty' }, 'This report has no rows.')
      : h(
          'div',
          { class: 'r-table-wrap' },
          h(
            'table',
            { class: 'r-table' },
            h('caption', { class: 'vh' }, `Coverage rows of ${report.target}`),
            h(
              'thead',
              {},
              h('tr', {}, ['Variable', 'Class', 'Provenance', 'Slot', 'Note'].map((t) => h('th', { scope: 'col' }, t))),
            ),
            h('tbody', {}, rows.map(rowEl)),
          ),
        ),
  );
}

function rowEl(r) {
  return h(
    'tr',
    { id: r.id, 'data-class': r.cls },
    h(
      'th',
      { scope: 'row', 'data-label': 'Variable' },
      r.explain
        ? h(
            'details',
            { class: 'trace' },
            h('summary', {}, code(r.variable)),
            h('p', {}, 'Trace it from the project:'),
            code(r.explain, 'cmd'),
          )
        : code(r.variable),
    ),
    h('td', { 'data-label': 'Class' }, h('span', { class: `prov ${r.seg}` }, r.cls)),
    h(
      'td',
      { 'data-label': 'Provenance' },
      r.provenance ? h('span', { class: `prov ${r.provenance}` }, r.provenance) : h('span', { class: 'r-none' }, 'not given'),
    ),
    h(
      'td',
      { 'data-label': 'Slot' },
      code(r.slot),
      r.reads ? h('span', { class: 'r-sub' }, 'reads ', joinCodes(r.reads.map((s) => code(s)))) : null,
      r.via.length
        ? h(
            'span',
            { class: 'r-sub' },
            'follows ',
            joinCodes(r.via.map((v) => (v.href ? h('a', { href: v.href }, code(v.variable)) : code(v.variable)))),
          )
        : null,
    ),
    h(
      'td',
      { 'data-label': 'Note' },
      r.deprecated
        ? h(
            'span',
            { class: 'r-dep' },
            h('span', { class: 'd-badge d-badge--warning' }, 'deprecated'),
            r.deprecated.reason ? [' ', r.deprecated.reason] : null,
            r.deprecated.by && r.deprecated.by !== r.slot ? [' (via ', code(r.deprecated.by), ')'] : null,
          )
        : null,
      r.note,
      r.description ? h('span', { class: 'r-sub r-desc' }, r.description) : null,
      r.meaning ? h('span', { class: 'r-sub' }, 'meaning ', code(r.meaning)) : null,
    ),
  );
}

const joinCodes = (nodes) => nodes.flatMap((n, i) => (i === 0 ? [n] : [', ', n]));

/**
 * The rows' class filter and search, on the article as it is now (server
 * rendered or drawn above). A `follows` link to a row the filters hide clears
 * them first, so the link always lands somewhere visible.
 */
export function wireReport(article) {
  const filters = article.querySelector('[data-role="filters"]');
  const tbody = article.querySelector('.r-table tbody');
  if (!filters) return;
  filters.hidden = false;
  if (!tbody) return;
  const rows = [...tbody.rows];
  const texts = rows.map((r) => r.textContent.toLowerCase());
  const search = filters.querySelector('input[type="search"]');
  const status = filters.querySelector('[data-role="status"]');

  const apply = () => {
    const cls = filters.querySelector('input[name="r-class"]:checked')?.value ?? '';
    const q = search.value.trim().toLowerCase();
    let shown = 0;
    rows.forEach((row, i) => {
      const show = (cls === '' || row.dataset.class === cls) && (q === '' || texts[i].includes(q));
      row.hidden = !show;
      if (show) shown++;
    });
    status.textContent = shown === rows.length ? `${rows.length} rows` : `Showing ${shown} of ${rows.length} rows`;
  };
  const reset = () => {
    search.value = '';
    filters.querySelector('input[name="r-class"][value=""]').checked = true;
    apply();
  };

  filters.addEventListener('change', apply);
  search.addEventListener('input', apply);
  tbody.addEventListener('click', (e) => {
    const link = e.target.closest('a[href^="#r-"]');
    if (!link) return;
    const target = document.getElementById(link.getAttribute('href').slice(1));
    if (target?.hidden) reset();
  });
  apply();
}
