/**
 * @transtyle/exporter-daisyui — emits daisyUI v5 theme blocks
 * (`@plugin "daisyui/theme" { … }`, Tailwind 4 era, OKLCH-native).
 *
 * Notable vs shadcn: daisyUI's `secondary`/`accent` are true BRAND roles —
 * they map from our brand slots directly, not from subtle surfaces. Same
 * words, different meanings per ecosystem; the mapping tables encode it
 * (docs/language.md "false friends").
 */

const S = 'semantic.color.';

/** slot → daisyUI variable; content = paired foreground slot. */
const COLOR_MAPPING = [
  { css: '--color-base-100', slot: `${S}background.base`, cls: 'native' },
  { css: '--color-base-200', slot: `${S}surface.base`, cls: 'native' },
  // base-300 is the third step of a background ramp; border is the closest tone we have
  { css: '--color-base-300', slot: `${S}border.base`, cls: 'approximated', note: 'bg-ramp step ← border tone' },
  { css: '--color-base-content', slot: `${S}text.base`, cls: 'native' },
  { css: '--color-primary', slot: `${S}primary.base`, cls: 'native' },
  { css: '--color-primary-content', slot: `${S}text-on-primary.base`, cls: 'native' },
  { css: '--color-secondary', slot: `${S}secondary.base`, cls: 'native', note: 'true brand secondary (unlike shadcn)' },
  { css: '--color-secondary-content', slot: `${S}text-on-secondary.base`, cls: 'native' },
  { css: '--color-accent', slot: `${S}accent.base`, cls: 'native' },
  { css: '--color-accent-content', slot: `${S}text-on-accent.base`, cls: 'native' },
  { css: '--color-neutral', slot: `${S}neutral.base`, cls: 'native' },
  { css: '--color-neutral-content', slot: `${S}text-on-neutral.base`, cls: 'native' },
  { css: '--color-info', slot: `${S}info.base`, cls: 'native' },
  { css: '--color-info-content', slot: `${S}text-on-info.base`, cls: 'native' },
  { css: '--color-success', slot: `${S}success.base`, cls: 'native' },
  { css: '--color-success-content', slot: `${S}text-on-success.base`, cls: 'native' },
  { css: '--color-warning', slot: `${S}warning.base`, cls: 'native' },
  { css: '--color-warning-content', slot: `${S}text-on-warning.base`, cls: 'native' },
  { css: '--color-error', slot: `${S}danger.base`, cls: 'native', note: 'name translation: danger → error' },
  { css: '--color-error-content', slot: `${S}text-on-danger.base`, cls: 'native' },
];

export default {
  name: 'daisyui',

  emit(normalized, ctx) {
    const era = ctx.targetConfig.options?.era ?? 'v5';
    if (era !== 'v5') throw new Error(`exporter-daisyui skeleton supports era "v5" only (got "${era}")`);

    // Mode polarity rule: bind mode names, never the default flag.
    const light = normalized.modes.light ?? normalized.modes[normalized.defaultMode];
    const dark = normalized.modes.dark;

    const coverage = [];
    const radius = light.get('semantic.radius.md');
    const blocks = [];

    const themeBlock = (map, mode, flags) => {
      const lines = [
        `@plugin "daisyui/theme" {`,
        `  name: "${ctx.projectName}-${mode}";`,
        ...flags,
        `  color-scheme: ${mode};`,
      ];
      for (const m of COLOR_MAPPING) {
        const entry = map.get(m.slot);
        if (!entry?.value) {
          if (mode === 'light') coverage.push({ variable: m.css, slot: m.slot, class: 'unsupported', note: 'slot missing from IR' });
          continue;
        }
        if (mode === 'light') {
          const provKind = entry.provenance.kind;
          const cls = m.cls === 'approximated' ? 'approximated' : (provKind === 'derived' ? 'derived' : m.cls);
          coverage.push({ variable: m.css, slot: m.slot, class: cls, provenance: provKind, ...(m.note && { note: m.note }) });
        }
        lines.push(`  ${m.css}: ${ctx.formatColor(entry.value)}; /* ${m.slot.replace('semantic.', '')} */`);
      }
      if (radius) {
        // daisyUI splits radius by component family; one authored radius feeds all three
        lines.push(`  --radius-selector: ${radius.value};`);
        lines.push(`  --radius-field: ${radius.value};`);
        lines.push(`  --radius-box: ${radius.value};`);
      }
      lines.push('}');
      return lines.join('\n');
    };

    blocks.push(themeBlock(light, 'light', ['  default: true;', '  prefersdark: false;']));
    if (dark) blocks.push(themeBlock(dark, 'dark', ['  prefersdark: true;']));

    if (radius) {
      coverage.push({ variable: '--radius-{selector,field,box}', slot: 'semantic.radius.md', class: 'approximated', provenance: radius.provenance.kind, note: 'one radius feeds three component families' });
    }
    coverage.push({ variable: '--depth / --noise / --size-*', slot: '—', class: 'dropped', note: 'daisyUI stylistic effects with no token semantics; theme uses daisyUI defaults' });

    const css = [
      '/*',
      ` * GENERATED by transtyle — do not edit; source: ${ctx.projectName} token files`,
      ' * Target: daisyUI (era: v5, Tailwind 4) · rules standard@1 (skeleton subset)',
      ' */',
      '',
      ...blocks,
      '',
    ].join('\n');

    return {
      files: [
        { path: 'daisyui.transtyle.css', contents: css, kind: 'stylesheet' },
        { path: 'usage.md', contents: renderUsage(ctx, coverage), kind: 'doc' },
      ],
      coverage,
    };
  },
};

function renderUsage(ctx, coverage) {
  const counts = {};
  for (const c of coverage) counts[c.class] = (counts[c.class] ?? 0) + 1;
  const summary = Object.entries(counts).map(([k, v]) => `${v} ${k}`).join(' · ');
  return `# Using this daisyUI theme

Generated from the **${ctx.projectName}** design system by transtyle (daisyUI v5, Tailwind 4). Coverage: ${summary}.

## Install

In your global CSS, after Tailwind and the daisyUI plugin:

\`\`\`css
@import "tailwindcss";
@plugin "daisyui" {
  themes: ${ctx.projectName}-light --default, ${ctx.projectName}-dark --prefersdark;
}
@import "./daisyui.transtyle.css";
\`\`\`

The light theme is the default; the dark theme activates via \`prefers-color-scheme\` (or set \`data-theme="${ctx.projectName}-dark"\` manually — standard daisyUI behavior).

## Notes

- daisyUI's \`secondary\`/\`accent\` are mapped from your **brand** secondary/accent — in shadcn the same words mean subtle surfaces. Same design system, correct meaning in each ecosystem.
- \`--color-base-300\` is approximated from your border tone (daisyUI wants a third background-ramp step the IR doesn't define; see report.json).
- Regenerate with \`transtyle build daisyui\`; never edit this file.
`;
}
