// GENERATED by transtyle — do not edit; source: examples/acme/tokens/
// Target: storybook (>=8 <10) · IR spec v0 (draft) · rules standard@1
// HAND-WRITTEN EXPECTED OUTPUT for the Phase 0 paper exercise, round 3
// (docs/exercises/phase0-storybook.md).
//
// Additive fragment: import from your own .storybook/manager.ts — we never
// overwrite user config files. Chrome is themed with the design system's
// NATIVE mode (Acme's `default: light` — the mode polarity rule): Storybook
// manager theming is static per boot, so the chrome wears the DS's default
// face. A dark-native DS (e.g. examples/cathode) would get `dark` here.
// Both variants are in theme.transtyle.ts for users who wire their own switch.

import { addons } from 'storybook/manager-api';
import { light } from './theme.transtyle';

addons.setConfig({ theme: light });
