// GENERATED by transtyle — do not edit; source: examples/acme/tokens/
// Target: storybook (>=8 <10) · IR spec v0 (draft) · rules standard@1
// HAND-WRITTEN EXPECTED OUTPUT for the Phase 0 paper exercise, round 3
// (docs/exercises/phase0-storybook.md).
//
// Composition per the exporter spec: `options.previewTargets = ["shadcn", "daisyui"]`.
// The import paths and the mode-toggle lines below are assembled by core from the
// SIBLING TARGETS' build manifests (artifact path + declared mode encoding) and
// injected via TargetContext — exporters never read each other's resolutions.
// Additive fragment: spread into your own .storybook/preview.ts.

import '../shadcn/globals.transtyle.css';       // sibling: shadcn · mode encoding: `.dark` class on <html>
import '../daisyui/daisyui.transtyle.css';      // sibling: daisyui · mode encoding: data-theme attribute
import { light, dark } from './theme.transtyle';

export const globalTypes = {
  colorScheme: {
    description: 'Design-system color scheme',   // mode dimension `color-scheme` → SB global toolbar: native
    toolbar: {
      title: 'Scheme',
      icon: 'mirror',
      items: [
        { value: 'light', title: 'Light' },       // mode names, never the default flag (mode polarity rule)
        { value: 'dark', title: 'Dark' },
      ],
      dynamicTitle: true,
    },
  },
};

export const initialGlobals = { colorScheme: 'light' };  // Acme's default mode

// One decorator drives BOTH siblings' encodings — assembled from their manifests (F18)
export const decorators = [
  (Story: any, context: any) => {
    const scheme = context.globals.colorScheme ?? 'light';
    const root = document.documentElement;
    root.classList.toggle('dark', scheme === 'dark');                    // shadcn
    root.setAttribute('data-theme', `acme-design-system-${scheme}`);     // daisyui
    return Story();
  },
];

export const parameters = {
  docs: {
    theme: light,  // docs pages follow the DS default mode; per-scheme docs theming is chrome-static in SB (see F18)
  },
  backgrounds: {
    // background.base per mode — so stories opted out of the decorator still sit on DS canvases
    options: {
      light: { name: 'acme light', value: '#ffffff' },   // background.base · authored
      dark: { name: 'acme dark', value: '#121419' },     // background.base[dark] · authored
    },
    grid: {
      cellSize: 16,       // space.4 (1rem) → px via config rem base · approximated (F16)
      cellAmount: 4,      // exporter default — no IR concept
      opacity: 0.35,      // exporter default
    },
  },
};
