// GENERATED by transtyle — do not edit; source: examples/acme/tokens/
// Target: storybook (>=8 <10) · IR spec v0 (draft) · rules standard@1
// HAND-WRITTEN EXPECTED OUTPUT for the Phase 0 paper exercise, round 3
// (docs/exercises/phase0-storybook.md). Hand-approximated hex — indicative only.
//
// Colors are emitted as hex, not OKLCH: Storybook's theming pipeline transforms
// chrome colors internally (polished), which does not parse oklch() — the
// per-target output-syntax choice ir.md provides for.

import { create } from 'storybook/theming';

export const light = create({
  base: 'light',

  colorPrimary: '#3a6ad4',        // primary.base · authored
  colorSecondary: '#3a6ad4',      // accent.base · [derived: alias-primary] — SB's actual highlight color (see F14 note)

  appBg: '#f8f9fb',               // surface.base · authored — chrome sidebar/app
  appContentBg: '#ffffff',        // background.base · authored — addon/docs panels
  appPreviewBg: '#ffffff',        // background.base · authored — the canvas is the DS's own canvas, not chrome (F18)
  appBorderColor: '#e4e7ec',      // border.base · authored
  appBorderRadius: 8,             // radius.md 0.5rem → px via config rem base 16 · approximated (F16)

  fontBase: '"Inter", system-ui, sans-serif',              // font.sans · authored
  fontCode: '"JetBrains Mono", ui-monospace, monospace',   // font.mono · authored

  textColor: '#21242e',           // text.base · authored
  textInverseColor: '#f8f9fb',    // text.base[dark] · cross-mode read (F15)
  textMutedColor: '#6b7383',      // text-muted.base · authored — ⚠ TST2101 borderline AA (same fixture finding)

  barBg: '#f8f9fb',               // surface.base · authored
  barTextColor: '#6b7383',        // text-muted.base · authored
  barHoverColor: '#2f57b0',       // primary.hover · [derived: OKLCH L−0.04] — first chrome consumer of a role state
  barSelectedColor: '#3a6ad4',    // primary.base · authored

  buttonBg: '#f1f3f6',            // neutral.subtle · [derived: mix(neutral.base, surface, 0.88)]
  buttonBorder: '#e4e7ec',        // border.base · authored
  booleanBg: '#f1f3f6',           // neutral.subtle · [derived]
  booleanSelectedBg: '#ffffff',   // surface-raised.base · [derived: raise(surface)]

  inputBg: '#ffffff',             // background.base · authored
  inputBorder: '#e4e7ec',         // border.base · authored
  inputTextColor: '#21242e',      // text.base · authored
  inputBorderRadius: 4,           // radius.sm · [derived: md × 0.5 — F8's rule, second consumer] → px · approximated (F16)

  brandTitle: 'acme-design-system',  // config `name` — not a token (F17)
  // brandUrl / brandImage: unsupported — no IR/config home for identity assets (F17);
  // pass through `options.brand` when the exporter is implemented
});

export const dark = create({
  base: 'dark',

  colorPrimary: '#3a6ad4',        // unchanged: autoDark=false, no authored dark brand (F7 — third target agreeing)
  colorSecondary: '#3a6ad4',

  appBg: '#21242e',               // surface.base[dark] · authored
  appContentBg: '#121419',        // background.base[dark] · authored
  appPreviewBg: '#121419',        // background.base[dark] · authored
  appBorderColor: '#363b47',      // border.base[dark] · authored
  appBorderRadius: 8,

  fontBase: '"Inter", system-ui, sans-serif',
  fontCode: '"JetBrains Mono", ui-monospace, monospace',

  textColor: '#f8f9fb',           // text.base[dark] · authored
  textInverseColor: '#21242e',    // text.base[light] · cross-mode read (F15)
  textMutedColor: '#9aa2b1',      // text-muted.base[dark] · authored

  barBg: '#21242e',
  barTextColor: '#9aa2b1',
  barHoverColor: '#5b86e8',       // primary.hover[dark] · [derived: L-delta flips in dark]
  barSelectedColor: '#5b86e8',    // [derived: lightened for dark visibility — mirrors the ring rule]

  buttonBg: '#363b47',            // neutral.subtle[dark] · [derived]
  buttonBorder: '#363b47',        // border.base[dark] · authored
  booleanBg: '#363b47',
  booleanSelectedBg: '#2b2f3a',   // surface-raised.base[dark] · [derived: raise(surface) lightens in dark]

  inputBg: '#121419',
  inputBorder: '#363b47',
  inputTextColor: '#f8f9fb',
  inputBorderRadius: 4,

  brandTitle: 'acme-design-system',
});
