// GENERATED by transtyle — do not edit; source: examples/acme/tokens/
// Target: storybook (>=8 <10) · IR spec v0 (draft) · rules standard@1
// EXPECTED OUTPUT for the Phase 0 paper exercise — written by hand in round 3,
// color values regenerated ENGINE-EXACT in round 8 (docs/exercises/
// phase0-shadcn-round8.md), applying round 6's fixture-freshness principle;
// the round-3 hand hexes live in git history. The hand run had also collapsed
// two distinct slots to one gray (neutral.subtle[dark] vs border.base[dark]) —
// the engine distinguishes them (#1d2127 vs #2a2e34).
//
// Colors are emitted as hex, not OKLCH: Storybook's theming pipeline transforms
// chrome colors internally (polished), which does not parse oklch() — the
// per-target output-syntax choice ir.md provides for.

import { create } from 'storybook/theming';

export const light = create({
  base: 'light',

  colorPrimary: '#026fd7',        // primary.base · authored
  colorSecondary: '#026fd7',      // accent.base · [derived: alias-primary] — SB's actual highlight color (see F14 note)

  appBg: '#f9fafc',               // surface.base · authored — chrome sidebar/app
  appContentBg: '#ffffff',        // background.base · authored — addon/docs panels
  appPreviewBg: '#ffffff',        // background.base · authored — the canvas is the DS's own canvas, not chrome (F18)
  appBorderColor: '#e2e5e9',      // border.base · authored
  appBorderRadius: 8,             // radius.md 0.5rem → px via config rem base 16 · approximated (F16)

  fontBase: '"Inter", system-ui, sans-serif',              // font.sans · authored
  fontCode: '"JetBrains Mono", ui-monospace, monospace',   // font.mono · authored

  textColor: '#171b20',           // text.base · authored
  textInverseColor: '#f9fafc',    // text.base[dark] · cross-mode read (F15)
  textMutedColor: '#6d7279',      // text-muted.base · authored — ⚠ TST2101 borderline AA (same fixture finding)

  barBg: '#f9fafc',               // surface.base · authored
  barTextColor: '#6d7279',        // text-muted.base · authored
  barHoverColor: '#005fc6',       // primary.hover · [derived: OKLCH L−0.05] — first chrome consumer of a role state
  barSelectedColor: '#026fd7',    // primary.base · authored

  buttonBg: '#edeff1',            // neutral.subtle · [derived: mix(neutral.base, surface, 0.92) — cartesian, F21]
  buttonBorder: '#e2e5e9',        // border.base · authored
  booleanBg: '#edeff1',           // neutral.subtle · [derived]
  booleanSelectedBg: '#ffffff',   // surface-raised.base · [derived: raise(surface)]

  inputBg: '#ffffff',             // background.base · authored
  inputBorder: '#e2e5e9',         // border.base · authored
  inputTextColor: '#171b20',      // text.base · authored
  inputBorderRadius: 4,           // radius.sm · [derived: md × 0.5 — F8's rule, second consumer] → px · approximated (F16)

  brandTitle: 'acme-design-system',  // config `name` — not a token (F17)
  // brandUrl / brandImage: unsupported — no IR/config home for identity assets (F17);
  // pass through `options.brand` when the exporter is implemented
});

export const dark = create({
  base: 'dark',

  colorPrimary: '#026fd7',        // unchanged: autoDark=false, no authored dark brand (F7 — third target agreeing)
  colorSecondary: '#026fd7',

  appBg: '#171b20',               // surface.base[dark] · authored
  appContentBg: '#080b0f',        // background.base[dark] · authored
  appPreviewBg: '#080b0f',        // background.base[dark] · authored
  appBorderColor: '#2a2e34',      // border.base[dark] · authored
  appBorderRadius: 8,

  fontBase: '"Inter", system-ui, sans-serif',
  fontCode: '"JetBrains Mono", ui-monospace, monospace',

  textColor: '#f9fafc',           // text.base[dark] · authored
  textInverseColor: '#171b20',    // text.base[light] · cross-mode read (F15)
  textMutedColor: '#9a9fa5',      // text-muted.base[dark] · authored

  barBg: '#171b20',
  barTextColor: '#9a9fa5',
  barHoverColor: '#207fe8',       // primary.hover[dark] · [derived: L-delta flips in dark]
  barSelectedColor: '#3186e9',    // ring.base[dark] · [derived: lightened for dark visibility — F3]

  buttonBg: '#1d2127',            // neutral.subtle[dark] · [derived]
  buttonBorder: '#2a2e34',        // border.base[dark] · authored
  booleanBg: '#1d2127',
  booleanSelectedBg: '#20242a',   // surface-raised.base[dark] · [derived: raise(surface) lightens in dark]

  inputBg: '#080b0f',
  inputBorder: '#2a2e34',
  inputTextColor: '#f9fafc',
  inputBorderRadius: 4,

  brandTitle: 'acme-design-system',
});
